### PR TITLE
Local content

### PR DESCRIPTION
**Pull request by brucejh99**
- use current displayed HTML to get metadata instead of a request
- some minor refactoring

### CODE REVIEW

**Comment by ddlan** [comment]
got this error when trying to cite `chrome://extensions/` where it used to work before. I don't think it really makes sense to cite local or browser specific pages, but just FYI.

Do we want to add an error popup here? Right now the loading animation plays indefinitely and an error is logged to console.

image

**Comment by brucejh99** [comment]
This is just citing the same stuff except getting the existing browser DOM instead of making a request for it. I think I see where the error's coming from will try to fix tomorrow

**Comment by brucejh99** [comment]
@ddlan fixed it I think. If it works on your computer I'm gonna build the new version and push to the store.

**Review by ddlan — APPROVED** [review]
Looks good to me 👍 working on my computer

**Pull request merged**
